# Generated by Django 4.1.4 on 2022-12-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_card_data_week_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card_data',
        ),
    ]
