# Generated by Django 4.1.4 on 2022-12-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
